const {chromium}=require('playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1040}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve('docs/review/abilities.html')).href);
 await page.locator('article').last().scrollIntoViewIfNeeded();
 await page.locator('article').first().scrollIntoViewIfNeeded();
 if(await page.locator('article').count()!==49)throw Error('Missing skills');
 await page.locator('#search').fill('Welding torch');
 if(await page.locator('article').count()!==1)throw Error('Search failed');
 await page.locator('article select').selectOption('rework');
 await page.locator('textarea').fill('Test note');await page.reload();
 await page.locator('#search').fill('Welding torch');
 if(await page.locator('textarea').inputValue()!=='Test note')throw Error('Notes not retained');
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();await downloadPromise;
 await page.locator('#search').fill('');await page.locator('#category').selectOption('movement');
 const movement=await page.locator('article').count();if(movement<5)throw Error('Category failed');
 await page.locator('#category').selectOption('all');
 await page.evaluate(()=>{localStorage.clear();window.scrollTo(0,0)});await page.reload();
 await page.screenshot({path:'output/ability-catalog17.png'});
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('CATALOG QA: 49 skills, filters, notes, export and narrow layout passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
